config/routes.rb
Spree::Core::Engine.routes.append do
  get 'about/index'
  match 'about', :to => "about#index"

  get 'return/index'
  match 'return', :to => "return#index"

  get 'tandc/index'
  match 'tandc', :to => "tandc#index"

  get 'faq/index'
  match 'faq', :to => "faq#index"

  get 'news_letter/index'
  match 'news_letter', :to => "news_letter#index"

  get 'contact_us/index'
  match 'contact_us', :to => "contact_us#index"

  get 'delivery/index'
  match 'delivery', :to => "delivery#index"

  get 'cupcake_decorations/index'
  match 'cupcake_decorations', :to => "cupcake_decorations#index"

  get 'site/index'
  match 'site', :to => "site#index"

  get 'sitemap/index'
  match 'sitemap', :to => "sitemap#index"

  namespace :admin do
    resource :google_merchants
  end

end

app/models/spree/google_merchant_configuration.rb
class Spree::GoogleMerchantConfiguration < Spree::Preferences::Configuration
  preference :google_merchant_title, :string, :default => 'My Spree Shop'
  preference :google_merchant_description, :string, :default => 'List of our products'
  preference :production_domain, :string, :default => 'http://www.myspreeshop.com/'
end

app/controllers/spree/about_controller.rb
module Spree
  class AboutController < BaseController

    def index
    end
  end
end

app/controllers/spree/admin/google_merchants_controller.rb
class Spree::Admin::GoogleMerchantsController < Spree::Admin::BaseController

  def update
    Spree::GoogleMerchant::Config.set(params[:preferences])

    respond_to do |format|
      format.html {
        redirect_to admin_google_merchants_path
      }
    end
  end

end

app/controllers/spree/contact_us_controller.rb
module Spree
  class ContactUsController < BaseController

    def index
    end
  end
end

app/controllers/spree/cupcake_decorations_controller.rb
module Spree
  class CupcakeDecorationsController < BaseController

    def index
      @products = Spree::Product.all
    end
  end
end

app/controllers/spree/delivery_controller.rb
module Spree
  class DeliveryController < BaseController

    def index
    end
  end
end

app/controllers/spree/faq_controller.rb
module Spree
  class FaqController < BaseController

    def index
    end
  end
end

app/controllers/spree/news_letter_controller.rb
module Spree
  class NewsLetterController < BaseController

    def index
    end
  end
end

app/controllers/spree/return_controller.rb
module Spree
  class ReturnController < BaseController

    def index
    end
  end
end

app/controllers/spree/sitemap_controller.rb
module Spree
  class SitemapController < BaseController
    def index
      @public_dir = "http://#{Spree::Config[:site_url]}/parties/"

      @products = Spree::Product.active.find(:all)
      @taxonomies = Spree::Taxonomy.all

      # Get Pages from static_content extension
      slugs_to_reject = ["sidebar"] # if want to exlude pages from the sitemap, enter the slugs here
      #slugs = []
      #sitemap_slugs = []
      #Page.all.each { |p| slugs << p.slug }
      #sitemap_slugs = slugs - slugs_to_reject
      #@pages = []
      #sitemap_slugs.each {|s| @pages << Page.find_by_slug(s) }

      respond_to do |format|
        format.html {  }
        format.rss {}
        format.xml { render :layout => false, :xml => _build_xml(_add_products_to_tax(_build_taxon_hash, true), @public_dir) }
        format.text do
          @nav = _add_products_to_tax(_build_taxon_hash, true)
          render :layout => false
        end
      end
    end

    private

    def returning(value)
      yield(value)
      value
    end

    def _build_xml(nav, public_dir)
      returning '' do |output|
        xml = Builder::XmlMarkup.new(:target => output, :indent => 2)
        xml.instruct!  :xml, :version => "1.0", :encoding => "UTF-8"
        xml.urlset( :xmlns => "http://www.sitemaps.org/schemas/sitemap/0.9" ) {
          xml.url {
            xml.loc public_dir
            xml.lastmod Date.today
            xml.changefreq 'daily'
            xml.priority '1.0'
          }
          nav.each do |k, v|
            xml.url {
              xml.loc public_dir + v['link']
              xml.lastmod v['updated'].xmlschema			  #change timestamp of last modified
              xml.changefreq 'weekly'
              xml.priority '0.8'
            }
          end
        }
      end
    end

    def _build_taxon_hash
      nav = Hash.new
      Spree::Taxon.find(:all).each do |taxon|
        tinfo = Hash.new
        tinfo['name'] = taxon.name
        tinfo['depth'] = taxon.permalink.split('/').size
        tinfo['link'] = 't/' + taxon.permalink
        tinfo['updated'] = taxon.updated_at
        nav[taxon.permalink] = tinfo
      end
      nav
    end

    def _add_products_to_tax(nav, multiples_allowed)
      Spree::Product.active.find(:all).each do |product|
        pinfo = Hash.new
        pinfo['name'] = product.name
        pinfo['link'] = 'products/' + product.permalink	# primary
        pinfo['updated'] = product.updated_at

        nav[pinfo['link']] = pinfo				# store primary
        # cleaner sitemap xml without this
        # if multiples_allowed
        #         product.taxons.each do |taxon|
        #           pinfo['depth'] = taxon.permalink.split('/').size + 1
        #           taxon_link = taxon.permalink + 'p/' + product.permalink
        #           new_pinfo = pinfo.clone
        #           new_pinfo['link'] = taxon_link
        #           nav[taxon_link] = new_pinfo
        #         end
        #       else
        #       end
      end
      nav
    end
  end
end

app/controllers/spree/tandc_controller.rb
module Spree
  class TandcController < BaseController

    def index
    end
  end
end

app/views/spree/about/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>About Us</h1>
<div>
    Lily and Max was created from the realisation that throwing a wonderful and special birthday celebration for your little ones can prove difficult and time consuming with very little choice of coordinating party ware readily available out there.
    </br></br>
    My husband and I celebrated our Daughter's 1st birthday in January 2011, however with her birthday falling so close to Christmas we found it really difficult to find both the time and the lovely items to put together a perfect little birthday party for her. We did manage to have a delightful little tea party for her but we felt we could have made it so much more special if we'd been able to find all the bits and pieces to create a wonderful party. So we've spent the last few months sourcing everything to make your little ones day that little bit more special without you having to dedicate a lot of your time finding everything you need.
    </br></br>
    Our party kits contain only high quality items that beautifully complement each other to make your little ones day all that more memorable. All kits contain a disposable tablecloth, paper plates and cups, bunting or garland, napkins, balloons, balloon ribbon, candles, cake slice boxes and party bags. We also offer some lovely extras that perfectly complement each of the theme's, these include center pieces, cupcake kits, cupcake stands and some fun extras like butterfly fairy wings and wands. Invitations and thank you cards are also available.
    </br></br>
    In just a few minutes you can order all the basics to help you create your wonderful party, all you need to do is provide the food, cake, games and fill the party bags with items of your choice. Keep an eye on our blog for tips on party food, cakes, games, party bag fillers and other great suggestions.
    </br></br>
    We really hope you find our party kits helpful. We’d love to hear how your party goes and see any photos you'd like to send us, and with your permission we'll include them in our blog. Please feel welcome to get in touch with us at <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a> or via facebook or twitter. We'd also be grateful for any feedback you might have.
    </br></br>
    Have fun!
    </br>
    Lauren x
  <p></p>
</div>

app/views/spree/admin/google_merchants/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t('edit_google_merchant_settings') %></h1>

<%= form_tag(admin_google_merchants_path, :method => :put) do %>
  <p>
    <label><%= t("google_merchant_title") %></label>
    <%= text_field_tag('preferences[google_merchant_title]', Spree::GoogleMerchant::Config[:google_merchant_title]) %>
  </p>
  <p>
    <label><%= t("google_merchant_description") %></label>
    <%= text_field_tag('preferences[google_merchant_description]', Spree::GoogleMerchant::Config[:google_merchant_description]) %>
  </p>
  <p>
    <label><%= t('production_domain') %></label>
    <%= text_field_tag('preferences[production_domain]', Spree::GoogleMerchant::Config[:production_domain])%>
  </p>


  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_google_merchants_url %>
  </p>
<% end %>

app/views/spree/admin/google_merchants/show.html.erb
<%= render :partial => '/spree/admin/shared/configuration_menu' %>

<h1><%= t("google_merchant_settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("google_merchant_title") %>:</th>
    <td><%= Spree::GoogleMerchant::Config[:google_merchant_title] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("google_merchant_description") %>:</th>
    <td><%= Spree::GoogleMerchant::Config[:google_merchant_description] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("production_domain") %>:</th>
    <td><%= Spree::GoogleMerchant::Config[:production_domain] %></td>
  </tr>
</table>

<p><%= link_to_with_icon 'edit', t("edit"), edit_admin_google_merchants_path, :id => 'admin_google_merchants_link' %></p>

app/views/spree/contact_us/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Contact Us</h1>
<div>
  <table class="address_details">
    <tr>
      <!--<td><img src="/assets/store/email.png" alt="email"></td>-->
      <td><h6>Email Address</h6></td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td><a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a></td>
    </tr>
    <tr>
      <!--<td><img src="/assets/store/telephone.png" alt="telephone"></td>-->
      <td><h6>Phone Number</h6></td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td>07900 345 398</td>
    </tr>
    <tr>
        <!--<td><img src="/assets/store/stamp-address.png" alt="address-stamp"></td>-->
        <td><h6>Address Details</h6></td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td>Lily and Max Ltd</td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td>42 Kempthorne Lane</td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td>Bath</td>
    </tr>
    <tr>
        <!--<td></td>-->
        <td>BA2 5DX</td>
    </tr>
  </table>
 <p></p>
</div>

app/views/spree/cupcake_decorations/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Cupcake Decorations</h1>

<%
  products = @products
%>

<% if products.map(&:cupcake_decoration).include? true  %>
<ul id="products" class="inline product-listing" data-hook>
  <% products.each do |product| %>
    <% if product.cupcake_decoration == true && (Spree::Config[:show_zero_stock_products] || product.has_stock?) %>
          <li id="product_<%= product.id %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
            <div class="product-image">
              <%= link_to small_image(product, :itemprop => "name"), product %>
            </div>
            <%= link_to truncate(product.name, :length => 50), product, :class => 'info', :itemprop => "name", :title => product.name %>
            <span class="price selling" itemprop="price"><%= number_to_currency product.price %></span>
          </li>
    <% end %>
  <% end %>
</ul>
<% end %>

app/views/spree/delivery/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Delivery</h1>
<div>
    Orders over the value of £70.00 qualify for free delivery. Orders that are under £70.00 will incur a delivery charge of £3.95.
    </br></br>
    We aim to despatch orders as soon as possible once your order is received and anticipate that orders will be delivered within one week. Please note that if an order is placed outside of business hours (Monday to Friday between 09.00 and 17.30 excluding Bank Holidays) your order will processed on the next working day and the estimate of a week should be taken from then.
    </br></br>
    If your order is for delivery to Northern Ireland or the “Highlands and Islands” please allow extra time for delivery.
    </br></br>
    Orders will be delivered by Royal Mail Recorded delivery. If delivery fails you will be left a card by Royal mail and will be able to collect your parcel from your local sorting office or arrange redelivery (see your attempted delivery card for details on how to do this).
  <p></p>
</div>

app/views/spree/faq/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Frequently Asked Questions</h1>
<div>
  <a href="#contact">How do I contact Lily and Max?</a>
  </br>
  <a href="#order_online">Do I have to order online?</a>
  </br>
  <a href="#secure">Is your website secure?</a>
  </br>
  <a href="#payment_options">What payment options do you accept</a>
  </br>
  <a href="#privacy_policy">What is your privacy policy?</a>
  </br>
  <a href="#free_delivery">How do I qualify for free delivery?</a>
  </br>
  <a href="#outside_uk">Do you deliver outside of the UK?</a>
  </br>
  <a href="#place_order">What happens when I place an order?</a>
  </br>
  <a href="#payment_taken">When is payment taken?</a>
  </br>
  <a href="#adding_items">Can I add an item to my order?</a>
  </br>
  <a href="#delivered_order">How is my order delivered?</a>
  </br>
  <a href="#delivery_times">How long does delivery take?</a>
  </br>
  <a href="#return_order">How do I return an order or item?</a>
  </br>
  <a href="#website_issues">I am having problems using the website?</a>
  </br></br>

  <a name="contact">How do I contact Lily and Max</a>
  </br>
    <b>E-mail: </b></b><a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a>
    </br>
    <b>Telephone: </b>07900 345 398
    </br>
    We are available to answer your calls between 09.00 and 17.30 Monday to Friday (excluding Bank Holidays), if your call is diverted to voicemail please feel welcome to leave a message including your contact number and we will return your call as soon as we can.
    </br>
    <b>Post: </b>You are welcome to write to us at the address below (please note our premises are not open to the public):
    Lily and Max Ltd, 42 Kempthorne Lane, Bath, BA2 5DX
  </br></br>

  <a name="order_online">Do I have to order online</a>
  </br>
    The easiest way to place your order is online, alternatively your order can be placed over the phone.
  </br></br>

  <a name="payment_options">What payment options do you accept</a>
  </br>
    We use paypal secure payment service to process our payments, but you are NOT required to have a paypal account to purchase items online.   
    Please note that your order will not be dispatched until we have confirmation of cleared funds. All advertised shipping times start from the time we receive cleared funds and your order is despatched.
    You can pay by Visa, Delta/Connect, Visa Electron, Maestro, Solo, MasterCard or PayPal.
    </br></br>
    Your order has been accepted when goods have been despatched. At that point we will also contact you by email confirming all that your order has been despatched and with details of how you can track your order.
    All prices stated are inclusive of VAT at the current rates and the total cost of the order is the price of the products ordered plus the delivery charge if applicable.
    All credit/debit cardholders are subject to validation checks and authorisation by the card issuer. If the issuer of your payment card raises any alerts due to discrepancies with your payment then we will notify you by email.
  </br></br>

  <a name="secure">Is your website secure</a>
  </br>
    All online purchases take place in a safe environment using the latest security technology to protect our customers.
    Sensitive information such as your credit card details, name and contact details are encrypted to ensure your orders remain private and protected over the Internet. We accept orders only from web browsers that permit communication through Secure Socket Layer (SSL) technology. This means you will only be able to place an order through a secure connection and information passed between your computer and our website cannot be read in the event that someone else intercepts it.
    If you have any questions regarding our credit card security policies please contact us via email at <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a>
  </br></br>

  <a name="privacy_policy">What is your privacy policy</a>
  </br>
    We are committed to protecting your privacy. We will only use the information that we collect about you lawfully (in accordance with the Data Protection Act 1998).
    We collect information about you for two reasons: firstly, to process your order and secondly, to provide you with the best possible service. We will not contact you in the future unless you have given us your consent. We will give you the chance to refuse any marketing email from us.
    We will never collect sensitive information about you without your explicit consent. The information we hold will be accurate and up to date. You can check the information that we hold about you by emailing us. If you find any inaccuracies we will delete or correct it promptly.
  </br></br>

  <a name="free_delivery">How do I qualify for free delivery</a>
  </br>
    Orders over the value of £70.00 qualify for free delivery. Orders that are under £70.00 will incur a delivery charge of £3.95.
  </br></br>

  <a name="outside_uk">Do you deliver outside of the UK</a>
    We're sorry we don't currently ship orders outside of the UK, if you are interested in having an order shipped outside of the UK please send us a quick email, it may be something we'll consider introducing at a later date.
  </br></br>

  <a name="place_order">What happens when I place an order</a>
  </br>
    When you place an order request on our website we will email you an acknowledgement which will confirm all relevant details. This acknowledgement is not acceptance of your order, which is at the point of despatch.
    We may need to refuse an order, this may result from one of the following reasons:
    <li>The product ordered being unavailable from stock</li>
    <li>We cannot obtain payment authorisation from your card issuer</li>
    <li>Errors within the product information including price or promotion</li>
    <li>If there are any problems with your order we will contact you. While we will look to resolve any difficulties quickly and look to reach a mutually acceptable solution, we need to state that the contract is governed by the laws of England and any dispute between us will be resolved exclusively in the courts of England. Your statutory rights are not affected.</li>
    <li>While we take all reasonable care, in so far as in our power to do so, to keep the details of your order and payment secure. However, in the absence of negligence on our part we cannot be held liable for any loss you may suffer if a third party procures unauthorised access to any data you provide when accessing or ordering from the website.</li>
    </br>
      <div style="border-style: solid; border-width:1px; padding: 5px">
      <h6 style="text-decoration: underline">Please note</h6>
        Some products and items for sale on this website are unsuitable for children under the age of <b>36 months</b> due to, but not limited to, small parts which may present a choking hazard or sharp points that may cause injury. We do not accept liability for any injury, loss or damage which occurs due to the products.
        All the items selected by Lily and Max, where required, comply with the European Toy Safety Regulations and bear the CE mark and age guides where appropriate. Please retain any packaging for future reference.
        <br>
        Adults should inflate balloons and supervise their use with children under <b>8 years</b>.
      </div>
    </br>

    We retain the right to change our pricing and discounts offered, at any time and without giving notice.
    If we can’t supply what you want, we promise to let you know as soon as we can.
    If you change your mind after placing an order, you may cancel your order before it is despatched by emailing us.  Once despatched we're afraid we aren't able to cancel it.
    From time to time we may have to change these terms and conditions without prior notice.
  </br></br>

  <a name="payment_taken">When is payment taken</a>
  </br>
    When an order is placed the funds for the order are reserved with your card issuer. The funds are not physically debited until the order is despatched.
  </br></br>

  <a name="adding_items">Can I add an item to my order</a>
  </br>
    If you would like to add an item to your order please contact us as soon as you can via email <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a> and if your order hasn't yet been despatched we will do our best to add the item to your order.
  </br></br>

  <a name="delivered_order">How is my order delivered</a>
  </br>
    Orders will be delivered by Royal Mail Recorded delivery. If delivery fails you will be left a card by Royal mail and will be able to collect your parcel from your local sorting office or arrange redelivery (see your attempted delivery card for details on how to do this.
  </br></br>

  <a name="delivery_times">How long does delivery take</a>
    We aim to despatch orders as soon as possible once your order is received and anticipate that  orders will be delivered within one week. Please note that if an order is placed outside of business hours (Monday to Friday between 09.00 and 17.30 excluding Bank Holidays) your order will processed on the next working day and the estimate of a week should be taken from then.
    If you require delivery sooner or your party is planned for a date sooner than 7 days from time of order please contact us and we will do everything we can to get your order despatched sooner
    If your order is for delivery to Northern Ireland or the “Highlands and Islands” please allow extra time for delivery.
  </br></br>

  <a name="return_order">How do I return an order or item</a>
  </br>
    We are sure you will be very happy with your order, however, if you are not completely satisfied with your purchase you may return your order back to us within 14 days of the date of despatch. If goods aren't returned to us within this time unfortunately we will be unable to process a return.
    All items returned should be in good condition, with all the original packaging fully intact and in saleable condition. We will consider the overall condition of the product being returned when making a refund. This does not affect your statutory rights in the event of faulty goods. If we find that the product has not been returned to us in a fully re saleable condition, we reserve the right to refuse a refund on the item. We aim to process returns within 5 working days of receipt.
    If any of your items arrive damaged or broken we must be notified of this within 48hours of receipt so we can arrange a replacement or refund. We are unable to replace or refund any items reported damaged after this time.
    Please note when sending a return, the parcel is your responsibility until it reaches us, therefore we recommend sending any returns by Royal Mail Recorded or Special Delivery so they fully traceable. Once the parcel has been received we will issue a refund providing it is returned in its original packing with all stickers in place and in a suitable condition for immediate resale. We regret that Postage and Packing cannot be refunded
    </br></br>
    <b>Returns</b>
    </br>
    Should be sent to the following address, please be sure to include your order number:
    </br>
    Lily and Max Ltd, 42 Kempthorne Lane, Bath, BA2 5DX
    </br></br>
    <b>Exchanges</b>
    </br>
    If you would like to exchange your pack for an alternative pack please notify us as soon as possible so we can ensure we have your replacement put by for you to avoid disappointment. Please note exchanges will need to processed within 14 days of despatch.
    </br></br>
    <b>Refunding the Delivery Charge</b>
    </br>
    If we have made a mistake on an item sent to you or it is faulty, we will refund the delivery charges incurred in returning the item to us.
    If you would like to discuss the exchange or return of any item, please email us at <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a>

  </br></br>
  <a name="website_issues">I am having probelms using the website</a>
  </br>
    To help us solve the issue for you, please email us at <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a> and include as many of the following details as possible, please cut and paste any error message that appeared on the screen into the email:
    <br>
    <li>Your Operating System (e.g. Windows XP, Mac OS 9.0)</li>
    <li>Internet Browser (e.g. Internet Explorer 6, Mozilla Firefox 3.5.1)</li>
    <li>What URL you are trying to access (e.g. http://www.aphex75.co.uk/store/contact_us)</li>
    <li>What time the problem occurred </li>
    <li>What the problem is</li>

  <p></p>
</div>

app/views/spree/news_letter/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Newsletter</h1>
<div>Keep an eye on our Newsletter for tips on partyfood, cakes, games, party bag fillers and other great suggestions. </div>
<p></p>
<div><h6>Newsletter signup at the bottom of the page</h6></div>

app/views/spree/return/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Returns</h1>
<div>
    We are sure you will be very happy with your order, however, if you are not completely satisfied with your purchase you may return your order back to us within 28 days of the date of despatch. If goods aren't returned to us within this time unfortunately we will be unable to process a return.
    </br></br>
    All items returned should be in good condition, with all the original packaging fully intact and in saleable condition. We will consider the overall condition of the product being returned when making a refund. This does not affect your statutory rights in the event of faulty goods. If we find that the product has not been returned to us in a fully re saleable condition, we reserve the right to refuse a refund on the item. We aim to process returns within 5 working days of receipt.
    </br></br>
    If any of your items arrive damaged or broken we must be notified of this within 48hours of receipt so we can arrange a replacement or refund. We are unable to replace or refund any items reported damaged after this time.
    </br></br>
    Please note when sending a return, the parcel is your responsibility until it reaches us, therefore we recommend sending any returns by Royal Mail Recorded or Special Delivery so they fully traceable. Once the parcel has been received we will issue a refund providing it is returned in its original packing with all stickers in place and in a suitable condition for immediate resale. We regret that Postage and Packing cannot be refunded
    </br></br>
    <b>Returns</b>
    </br>
    Should be sent to the following address, please be sure to include your order number:
    </br></br>
    Lily and Max Ltd,</br>42 Kempthorne Lane,</br>Bath,</br>BA2 5DX
    </br></br>
    <b>Exchanges</b>
    </br>
    If you would like to exchange your pack for an alternative pack please notify us as soon as possible so we can ensure we have your replacement put by for you to avoid disappointment. Please note exchanges will need to processed within 14 days of despatch.
    </br></br>
    <b>Refunding the Delivery Charge</b>
    </br>
    If we have made a mistake on an item sent to you or it is faulty, we will refund the delivery charges incurred in returning the item to us.
    If you would like to discuss the exchange or return of any item, please email us at <a href="mailto:customerservice@aphex75.co.uk">customerservice@aphex75.co.uk</a>
  <p></p>
</div>

app/views/spree/sitemap/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<p></p>
<h1>Sitemap</h1>
<%= link_to Spree::Config[:site_name], @public_dir %><br />
<% unless @pages.blank? %>
  <ul>
  <% @pages.each do |page| %>
    <li><%= link_to page.title, @public_dir + page.slug %></li>
  <% end %>
  </ul>
<% end %>
<% unless @taxonomies.blank? %>  
  <% @taxonomies.each do |taxonomy| %>
    <% taxons = Spree::Taxon.find_all_by_taxonomy_id(taxonomy.id) %>
    <h3><%= taxonomy.name %></h3>
    <ul>
    <% taxons.each do |taxon| %>
      <% unless "t/#{taxon.name}" == taxonomy.name %><li><%= link_to taxon.name, @public_dir + "t/" + taxon.permalink %></li><% end %>
    <% end %>
    </ul>
  <% end %>
  
<% end %>
<% unless @products.blank? %>
  <h3>Products</h3>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, @public_dir + "products/" + product.permalink %></li>
    <% end %>
  </ul>
<% end %>

app/views/spree/sitemap/index.text.erb
<%= @public_dir %>
<% @nav.sort.each do |k,v| -%>
<%= @public_dir %><%= v['link'] %>
<% end -%>